import type { SynthParams } from "../types";

const BASE: SynthParams = {
  spectralTilt: 0,
  harmonicSpread: 0.5,
  harmonicDensity: 0.5,
  oddEvenBalance: 0.5,
  inharmonicity: 0,
  spectralSmoothing: 0.3,
  amplitudeThreshold: 0.05,
  excitationSource: "SpectralHarmonics",
  attackSharpness: 0.5,
  noiseMix: 0.1,
  oscMix: 0.5,
  excitationEnergy: 0.7,
  energyThreshold: 0.12,
  amplitudeGain: 1.5,
  amplitudeFloor: 0.05,
  impulseWidth: 0.5,
  energyCompressor: 0,
  playbackSpeed: 1.0,
  canvasDuration: 8,
  loopStart: 0,
  loopEnd: 1,
  debugMode: false,
  resonatorType: "String",
  tension: 0.5,
  damping: 0.3,
  resonance: 0.6,
  decayTime: 0.5,
  brightness: 0.5,
  sustainEnergy: 0,
  resonatorMorph: 0,
  pickupPosition: 0.5,
  bodyModel: "None",
  bodySize: 0.5,
  bodyMix: 0,
  driftAmount: 0,
  driftRate: 0.3,
  filterType: "Lowpass",
  filterCutoff: 0.8,
  filterResonance: 0.2,
  filterDrive: 0,
  attack: 0.02,
  decay: 0.2,
  sustain: 0.6,
  release: 0.3,
  lfoWave: "Sine",
  lfoRate: 0.2,
  lfoDepth: 0,
  lfoTarget: "Pitch",
  chorusEnabled: false,
  chorusMix: 0.3,
  delayEnabled: false,
  delayMix: 0.3,
  reverbEnabled: false,
  reverbMix: 0.3,
  chordMode: false,
  chordType: "Major",
  chordInversion: "Root",
  chordSpread: 1,
  chordSize: 3,
  strumMode: false,
  strumSpeed: 50,
  chordDetune: 0,
  panSpread: 0.3,
  scaleLock: "Chromatic",
  rootNote: "C",
  progressionMode: false,
  progressionSelector: "I IV V",
  progressionSpeed: 4,
};

export const FACTORY_PRESETS: Record<string, SynthParams> = {
  "Spectral Violin": {
    ...BASE,
    resonatorType: "BowedString",
    tension: 0.75,
    damping: 0.15,
    resonance: 0.8,
    decayTime: 0.7,
    brightness: 0.65,
    sustainEnergy: 0.7,
    resonatorMorph: 0.2,
    pickupPosition: 0.35,
    bodyModel: "ViolinBody",
    bodySize: 0.45,
    bodyMix: 0.6,
    driftAmount: 0.08,
    driftRate: 0.4,
    filterType: "Lowpass",
    filterCutoff: 0.75,
    filterResonance: 0.3,
    attack: 0.08,
    decay: 0.15,
    sustain: 0.8,
    release: 0.4,
    chorusEnabled: true,
    chorusMix: 0.25,
    reverbEnabled: true,
    reverbMix: 0.2,
    excitationSource: "AirFlow",
    excitationEnergy: 0.75,
  },
  "Glass Bell": {
    ...BASE,
    resonatorType: "MetalPlate",
    tension: 0.85,
    damping: 0.05,
    resonance: 0.9,
    decayTime: 0.82,
    brightness: 0.82,
    sustainEnergy: 0,
    inharmonicity: 0.6,
    resonatorMorph: 0.7,
    pickupPosition: 0.7,
    bodyModel: "MetalChamber",
    bodySize: 0.3,
    bodyMix: 0.4,
    filterType: "Bandpass",
    filterCutoff: 0.65,
    filterResonance: 0.7,
    attack: 0.001,
    decay: 0.25,
    sustain: 0.0,
    release: 1.2,
    reverbEnabled: true,
    reverbMix: 0.5,
    excitationSource: "PulseStrike",
    attackSharpness: 0.95,
    excitationEnergy: 0.9,
    impulseWidth: 0.08,
    amplitudeGain: 2.0,
    energyThreshold: 0.08,
  },
  "Harmonic Harp": {
    ...BASE,
    resonatorType: "String",
    tension: 0.68,
    damping: 0.18,
    resonance: 0.68,
    decayTime: 0.7,
    brightness: 0.58,
    sustainEnergy: 0,
    bodyModel: "GuitarBody",
    bodySize: 0.55,
    bodyMix: 0.45,
    attack: 0.001,
    decay: 0.2,
    sustain: 0.0,
    release: 0.8,
    reverbEnabled: true,
    reverbMix: 0.3,
    delayEnabled: true,
    delayMix: 0.18,
    excitationSource: "SpectralHarmonics",
    attackSharpness: 0.78,
    harmonicDensity: 0.6,
    harmonicSpread: 0.6,
    impulseWidth: 0.1,
    amplitudeGain: 1.8,
    energyThreshold: 0.08,
  },
  "Pipe Organ Spectrum": {
    ...BASE,
    resonatorType: "TubeAirColumn",
    tension: 0.5,
    damping: 0.08,
    resonance: 0.85,
    decayTime: 0.9,
    brightness: 0.5,
    sustainEnergy: 0.95,
    resonatorMorph: 0.1,
    bodyModel: "WoodBox",
    bodySize: 0.7,
    bodyMix: 0.35,
    filterType: "Lowpass",
    filterCutoff: 0.75,
    filterResonance: 0.15,
    attack: 0.05,
    decay: 0.1,
    sustain: 0.95,
    release: 0.25,
    harmonicDensity: 0.8,
    oddEvenBalance: 0.7,
    excitationSource: "AirFlow",
    excitationEnergy: 0.95,
  },
  "Metal Drone": {
    ...BASE,
    resonatorType: "MetalPlate",
    tension: 0.7,
    damping: 0.05,
    resonance: 0.95,
    decayTime: 0.9,
    brightness: 0.7,
    sustainEnergy: 0.9,
    inharmonicity: 0.4,
    resonatorMorph: 0.5,
    bodyModel: "MetalChamber",
    bodySize: 0.6,
    bodyMix: 0.5,
    filterType: "Bandpass",
    filterCutoff: 0.55,
    filterResonance: 0.5,
    attack: 0.1,
    decay: 0.2,
    sustain: 0.9,
    release: 0.6,
    chorusEnabled: true,
    chorusMix: 0.2,
    reverbEnabled: true,
    reverbMix: 0.35,
    excitationSource: "OscillatorStack",
    excitationEnergy: 0.95,
  },
  "Resonant Pad": {
    ...BASE,
    resonatorType: "HybridMorph",
    tension: 0.45,
    damping: 0.1,
    resonance: 0.75,
    decayTime: 0.8,
    brightness: 0.4,
    sustainEnergy: 0.5,
    resonatorMorph: 0.4,
    filterType: "Lowpass",
    filterCutoff: 0.55,
    filterResonance: 0.4,
    attack: 0.4,
    decay: 0.4,
    sustain: 0.7,
    release: 0.8,
    lfoWave: "Sine",
    lfoRate: 0.15,
    lfoDepth: 0.15,
    lfoTarget: "FilterCutoff",
    chorusEnabled: true,
    chorusMix: 0.4,
    reverbEnabled: true,
    reverbMix: 0.55,
    excitationSource: "SpectralHarmonics",
    excitationEnergy: 0.6,
    harmonicSpread: 0.7,
  },
  "Drum Resonator": {
    ...BASE,
    resonatorType: "DrumMembrane",
    tension: 0.35,
    damping: 0.6,
    resonance: 0.5,
    decayTime: 0.2,
    brightness: 0.6,
    sustainEnergy: 0,
    resonatorMorph: 0.1,
    filterType: "Bandpass",
    filterCutoff: 0.45,
    filterResonance: 0.45,
    attack: 0.001,
    decay: 0.08,
    sustain: 0.1,
    release: 0.15,
    reverbEnabled: true,
    reverbMix: 0.2,
    excitationSource: "NoiseBurst",
    attackSharpness: 0.95,
    noiseMix: 0.7,
    excitationEnergy: 0.95,
  },
  "Alien Instrument": {
    ...BASE,
    resonatorType: "HybridMorph",
    tension: 0.6,
    damping: 0.15,
    resonance: 0.85,
    decayTime: 0.6,
    brightness: 0.75,
    sustainEnergy: 0.3,
    inharmonicity: 0.9,
    resonatorMorph: 0.8,
    pickupPosition: 0.25,
    filterType: "Bandpass",
    filterCutoff: 0.6,
    filterResonance: 0.65,
    attack: 0.02,
    decay: 0.2,
    sustain: 0.5,
    release: 0.5,
    lfoWave: "Random",
    lfoRate: 0.4,
    lfoDepth: 0.3,
    lfoTarget: "ResonatorTension",
    chorusEnabled: true,
    chorusMix: 0.5,
    reverbEnabled: true,
    reverbMix: 0.4,
    driftAmount: 0.25,
    driftRate: 0.6,
    excitationSource: "OscillatorStack",
    excitationEnergy: 0.8,
    harmonicDensity: 0.3,
  },
  "Ambient Drone": {
    ...BASE,
    resonatorType: "TubeAirColumn",
    tension: 0.5,
    damping: 0.05,
    resonance: 0.9,
    decayTime: 0.95,
    brightness: 0.35,
    sustainEnergy: 0.95,
    resonatorMorph: 0.15,
    filterType: "Lowpass",
    filterCutoff: 0.6,
    filterResonance: 0.3,
    attack: 0.4,
    decay: 0.5,
    sustain: 0.9,
    release: 1.0,
    lfoWave: "Sine",
    lfoRate: 0.08,
    lfoDepth: 0.2,
    lfoTarget: "SpectralTilt",
    chorusEnabled: true,
    chorusMix: 0.35,
    reverbEnabled: true,
    reverbMix: 0.7,
    driftAmount: 0.12,
    driftRate: 0.2,
    excitationSource: "AirFlow",
    excitationEnergy: 0.9,
    harmonicSpread: 0.8,
    chordMode: true,
    chordType: "OctaveStack",
    panSpread: 0.7,
  },
  "Experimental Hybrid": {
    ...BASE,
    resonatorType: "HybridMorph",
    tension: 0.55,
    damping: 0.2,
    resonance: 0.7,
    decayTime: 0.65,
    brightness: 0.6,
    sustainEnergy: 0.4,
    inharmonicity: 0.5,
    resonatorMorph: 0.9,
    pickupPosition: 0.6,
    filterType: "Highpass",
    filterCutoff: 0.35,
    filterResonance: 0.4,
    attack: 0.05,
    decay: 0.3,
    sustain: 0.55,
    release: 0.45,
    lfoWave: "Triangle",
    lfoRate: 0.25,
    lfoDepth: 0.25,
    lfoTarget: "Pitch",
    chorusEnabled: true,
    chorusMix: 0.3,
    delayEnabled: true,
    delayMix: 0.25,
    reverbEnabled: true,
    reverbMix: 0.35,
    driftAmount: 0.18,
    driftRate: 0.5,
    excitationSource: "OscillatorStack",
    excitationEnergy: 0.75,
    harmonicDensity: 0.65,
    spectralTilt: 0.2,
    oddEvenBalance: 0.4,
  },
  // ── New varied presets ─────────────────────────────────────────────────────
  "Koto Pluck": {
    ...BASE,
    resonatorType: "String",
    tension: 0.8,
    damping: 0.35,
    resonance: 0.55,
    decayTime: 0.45,
    brightness: 0.72,
    sustainEnergy: 0,
    resonatorMorph: 0.05,
    pickupPosition: 0.3,
    bodyModel: "WoodBox",
    bodySize: 0.6,
    bodyMix: 0.3,
    filterType: "Lowpass",
    filterCutoff: 0.82,
    filterResonance: 0.15,
    attack: 0.001,
    decay: 0.18,
    sustain: 0.0,
    release: 0.4,
    reverbEnabled: true,
    reverbMix: 0.2,
    excitationSource: "PulseStrike",
    attackSharpness: 0.92,
    excitationEnergy: 0.9,
    impulseWidth: 0.1,
  },
  "Crystal Marimba": {
    ...BASE,
    resonatorType: "MetalPlate",
    tension: 0.88,
    damping: 0.25,
    resonance: 0.75,
    decayTime: 0.6,
    brightness: 0.85,
    sustainEnergy: 0,
    inharmonicity: 0.2,
    resonatorMorph: 0.4,
    pickupPosition: 0.6,
    bodyModel: "MetalChamber",
    bodySize: 0.4,
    bodyMix: 0.5,
    filterType: "Bandpass",
    filterCutoff: 0.72,
    filterResonance: 0.5,
    attack: 0.001,
    decay: 0.22,
    sustain: 0.0,
    release: 0.6,
    reverbEnabled: true,
    reverbMix: 0.35,
    excitationSource: "PulseStrike",
    attackSharpness: 0.85,
    excitationEnergy: 0.88,
    impulseWidth: 0.08,
  },
  "Bowed Glass": {
    ...BASE,
    resonatorType: "BowedString",
    tension: 0.82,
    damping: 0.04,
    resonance: 0.92,
    decayTime: 0.85,
    brightness: 0.9,
    sustainEnergy: 0.8,
    inharmonicity: 0.55,
    resonatorMorph: 0.6,
    pickupPosition: 0.75,
    bodyModel: "MetalChamber",
    bodySize: 0.25,
    bodyMix: 0.55,
    filterType: "Bandpass",
    filterCutoff: 0.68,
    filterResonance: 0.75,
    attack: 0.12,
    decay: 0.2,
    sustain: 0.85,
    release: 0.9,
    reverbEnabled: true,
    reverbMix: 0.6,
    chorusEnabled: true,
    chorusMix: 0.3,
    excitationSource: "AirFlow",
    attackSharpness: 0.3,
    excitationEnergy: 0.8,
  },
  "Deep Thunder": {
    ...BASE,
    resonatorType: "DrumMembrane",
    tension: 0.18,
    damping: 0.1,
    resonance: 0.8,
    decayTime: 0.85,
    brightness: 0.3,
    sustainEnergy: 0.2,
    resonatorMorph: 0.3,
    bodyModel: "WoodBox",
    bodySize: 0.9,
    bodyMix: 0.7,
    filterType: "Lowpass",
    filterCutoff: 0.35,
    filterResonance: 0.6,
    attack: 0.001,
    decay: 0.5,
    sustain: 0.1,
    release: 1.0,
    reverbEnabled: true,
    reverbMix: 0.8,
    excitationSource: "NoiseBurst",
    attackSharpness: 0.98,
    noiseMix: 0.9,
    excitationEnergy: 1.0,
    impulseWidth: 0.04,
  },
  "Flute Breath": {
    ...BASE,
    resonatorType: "TubeAirColumn",
    tension: 0.42,
    damping: 0.12,
    resonance: 0.72,
    decayTime: 0.7,
    brightness: 0.6,
    sustainEnergy: 0.6,
    resonatorMorph: 0.08,
    pickupPosition: 0.5,
    bodyModel: "None",
    filterType: "Bandpass",
    filterCutoff: 0.65,
    filterResonance: 0.25,
    attack: 0.08,
    decay: 0.15,
    sustain: 0.75,
    release: 0.5,
    reverbEnabled: true,
    reverbMix: 0.3,
    chorusEnabled: true,
    chorusMix: 0.15,
    driftAmount: 0.06,
    driftRate: 0.3,
    excitationSource: "AirFlow",
    attackSharpness: 0.2,
    noiseMix: 0.5,
    excitationEnergy: 0.7,
  },
  "Acid String": {
    ...BASE,
    resonatorType: "String",
    tension: 0.72,
    damping: 0.22,
    resonance: 0.88,
    decayTime: 0.55,
    brightness: 0.78,
    sustainEnergy: 0,
    resonatorMorph: 0.15,
    pickupPosition: 0.2,
    bodyModel: "None",
    filterType: "Lowpass",
    filterCutoff: 0.45,
    filterResonance: 0.88,
    filterDrive: 0.6,
    attack: 0.005,
    decay: 0.12,
    sustain: 0.0,
    release: 0.25,
    lfoWave: "Sine",
    lfoRate: 0.35,
    lfoDepth: 0.5,
    lfoTarget: "FilterCutoff",
    reverbEnabled: false,
    delayEnabled: true,
    delayMix: 0.25,
    excitationSource: "PulseStrike",
    attackSharpness: 0.88,
    excitationEnergy: 0.95,
    impulseWidth: 0.07,
  },
};

export const PRESET_NAMES = Object.keys(FACTORY_PRESETS);
